apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: infinity-search-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: infinity-search-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
