<<EOT
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: -----BEGIN CERTIFICATE-----
MIIELTCCApWgAwIBAgIRAPb91s64S2nrQyTbAeBBOkMwDQYJKoZIhvcNAQELBQAw
LzEtMCsGA1UEAxMkYTI5NDIyOTgtZDU3MS00YjIyLWE1YmItNWU3NWExNTEzM2Qz
MCAXDTI0MDUxODEwNTYyNloYDzIwNTQwNTExMTE1NjI2WjAvMS0wKwYDVQQDEyRh
Mjk0MjI5OC1kNTcxLTRiMjItYTViYi01ZTc1YTE1MTMzZDMwggGiMA0GCSqGSIb3
DQEBAQUAA4IBjwAwggGKAoIBgQCHf/A4foo1L6X6Ed72fACPe6iwLunwPSGjNBbw
SiqQvmxNWGgbTRv7F7LkkJk6IkY0IW2zKnvQSr6cRAghkbhEjKHri9vKKA1i/EdF
XPZxAbrRbrapsx9ibu/c17xPBK2rcA0k25GlOVSYVhBm8vJ+hUdxjWrmv4q88UMP
HvHpLD3XzDbxddR5fFlUFvqQYotZoUjkFFg9rv3zB7nT426oAab+7iAERueg4Ta6
UxQP3fSZ+IZcIqgYzSo3S9xJsDs3Ejs2AdmR9pswbX4GkHqjEFfcf1+HEd0SX9xl
eRL79uLvLMenc5tiXi0TSgnkY1PJO3IzTSsGL2nLeweRzebc5bZ0qmM+fMh0namv
dSeOqDx3Ez3okZh3HMtdtjr/hu3E7D0eWcIz4mcaCayukJL+3sXhuM7zYZVH3kPI
H9RlfVRRMYqlOdTzs8kNLyzqthPYR16Tcf7WNUrCLlr5JohInYQz8xW0rMy6g9Cj
rhpgmkr5MIgXL3r2TGQGA0fhIsUCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgIEMA8G
A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFP/9OBNj38CsX2Gbaf32BFLv9SQKMA0G
CSqGSIb3DQEBCwUAA4IBgQAxocbxNyGD3tU8yjVLwiYpnh/kE3GUv7ThJ/Zh2Hf8
iBRfb2AO13HL1MCDWr4ib+3zE1TJxtOBJruQstZkZMWEi3mgIiQm0DvNa60giJyf
QOeM3Gz/bmOsrihns5sIRXN3KDNxrPz9icBxft+RWc/K/Efp6WGdL3MGl9hui9EP
tQhwS4fvl3WqCoCf75o8VpergNM5Xte+ko8AKgS1WbBiPsoDVGM35ns5WfTd3/G8
TX3pzvLk5INDnBEp6GbZHCStxSwrzVVRbq0B7fDSkZl3fR/7GVVX4ySymWxkdlyA
pRmoWsqyvewQ3JtMFcKEC0pGBDr37jCmQQOr6NwCRQgcYHWFavmparfptXdE3eJr
LtTrmNPf9g0Vg60Kd2fsC6BA9JOLodX5nNCUgh4Pe16/FiCcKCRrNnuv8uNPdaVr
uc39qLyq7hps5Rlwd0LveVCNdhCCC3drwKZvvH3Pb86QCcL+DD3xduuigpiBbopL
PgdEF3rkrDcO3GWHvMyXHA4=
-----END CERTIFICATE-----

    server: https://34.170.255.13
  name: search-engine-cluster
contexts:
- context:
    cluster: search-engine-cluster
    user: search-engine-cluster
  name: search-engine-cluster
current-context: search-engine-cluster
users:
- name: search-engine-cluster
  user:
    client-certificate-data: 
    client-key-data: 

EOT
